services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-cq4k12o8fa8c73fqpheg-a.oregon-postgres.render.com/todolist_db_24d1
      - SPRING_DATASOURCE_USERNAME=todolist_db_24d1_user
      - SPRING_DATASOURCE_PASSWORD=b732bDRVRWK8VCG7YfdgUUxG0fg6JAr3
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  db:
    image: 'postgres:13.1-alpine'
    container_name: postgres
    environment:
      POSTGRES_USER: todolist_db_24d1_user
      POSTGRES_PASSWORD: b732bDRVRWK8VCG7YfdgUUxG0fg6JAr3
      POSTGRES_DB: todolist_db_24d1
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data: